title: Resurrexit
description: "Un parcours pour vivre avec le Christ Ressuscité pendant le Temps pascal"
baseurl: "/Parcours-Resurrexit"
url: "https://benoitvillage-84.github.io"

# Date de début du parcours (Dimanche de Pâques)
parcours_start: "2025-04-05"

markdown: kramdown
permalink: pretty

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
