title: Resurrexit
description: "Un parcours pour vivre avec le Christ Ressuscité pendant le temps Pascal"
baseurl: ""
url: "https://go.parcours-resurrexit.com"

# Date de début du parcours (Dimanche de Pâques)
parcours_start: "2026-04-03"

markdown: kramdown
permalink: pretty

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
